language: node_js

sudo: false

cache:
  apt: true
  npm: true

node_js:
  - "10"
  - "12"
  - "node"

script:
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

#install:
#  - npm install

notifications:
  email: false
